# Generated by Django 4.0.6 on 2022-07-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Hi world', max_length=100),
            preserve_default=False,
        ),
    ]
