# Generated by Django 4.0.6 on 2022-07-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0002_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Активный', 'Активный'), ('Выполнен', 'Выполнен'), ('Отменён', 'Отменён')], default='Активный', max_length=30),
        ),
    ]
