# Generated by Django 4.0.6 on 2022-07-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, null=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('is_bot', models.BooleanField()),
            ],
        ),
    ]
