# Generated by Django 4.0.6 on 2022-07-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_bot',
        ),
    ]
