# Generated by Django 4.0.6 on 2022-07-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0002_remove_telegramuser_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='phone_num',
            field=models.CharField(default='+99898989898', max_length=30),
            preserve_default=False,
        ),
    ]
