# Generated by Django 4.0.6 on 2022-07-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0004_telegramstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramstate',
            name='context',
            field=models.JSONField(null=True),
        ),
    ]
