# Generated by Django 4.0.6 on 2022-07-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0005_alter_telegramstate_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramstate',
            name='id',
        ),
        migrations.RemoveField(
            model_name='telegramstate',
            name='user',
        ),
        migrations.AddField(
            model_name='telegramstate',
            name='user_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
