# Generated by Django 4.0.6 on 2022-07-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0006_remove_telegramstate_id_remove_telegramstate_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
